### PR TITLE
setColor now keeps the color in the object properties

### PR DESCRIPTION
**Pull request by neilstockbridge**

### CODE REVIEW

**Comment by z3dev** [comment]
@neilstockbridge thanks for the changes.

i have a few questions about the changes. what there any effect on the performance of the veiwer? what browsers did you test with?

**Comment by neilstockbridge** [comment]
Whoops, sorry.  I only intended for the color patch to be included in the pull request.

The change event only seems to be fired when the camera is moved and the `cameraChanged` function seems to complete in less than a millisecond on an i7-2617M.  I tested with Chromium 52 (no webGL) and Firefox 49 (with webGL).  It does assume support for `localStorage`.  Are there any changes or further testing you'd like to see?  This feature is handy for me because I edit the design file on the server and reload the page to see the changes, so having the camera in the same position means that I can see small changes to the model, but maybe not so useful in general?

**Comment by z3dev** [comment]
@neilstockbridge No problem. These are great changes.

I'll give these changes some further testing on mobile devices. If I don't find any issues with performance then consider these changes included.

**Comment by neilstockbridge** [comment]
Proposed support for "CSG.featureSize" (please rename if desired).  The idea is that instead of specifying a `resolution`, `featureSize` is specified, which is the approximate length of the edges used to approximate circles.  Specifying a featureSize of 1mm will use more segments for larger circles and fewer for smaller circles.  When printed, larger circles do not appear rougher than smaller ones (if given the same resolution).  A larger featureSize can be used for faster rendering, smaller when exporting for printing.

**Comment by z3dev** [comment]
> Proposed support for "CSG.featureSize" (please rename if desired). The idea is that instead of specifying a `resolution`, `featureSize` is specified, which is the approximate length of the edges used to approximate circles. Specifying a featureSize of 1mm will use more segments for larger circles and fewer for smaller circles. When printed, larger circles do not appear rougher than smaller ones (if given the same resolution). A larger featureSize can be used for faster rendering, smaller when exporting for printing.

@neilstockbridge This is a good feature request. But, this repository is now part of OpenJSCAD.org repository, part of the JSCAD project. Can you open a new issue there?

**Comment by z3dev** [comment]
@neilstockbridge these changes are good but this version of the CSG library is no longer maintained.

The actively maintained version is now part of JSCAD OpenJSCAD.org repository.

And, you will be happy as well because...
- Geometry has a single ‘color’ attribute
- A utility function exists to calculate ‘segments’ based upon minimum angle or length

I think you can close this pull request.

**Pull request closed without merging**
