### PR TITLE
Elliptic cylinder

### PR DESCRIPTION
**Pull request by dav-m85**
Backporting https://github.com/Spiritdude/OpenJSCAD.org/pull/94/files to correct location.

### CODE REVIEW

**Comment by kaosat-dev** [comment]
@dav-m85  could you please backport it again to https://github.com/jscad/csg.js ? :) pretty please ?

**Comment by z3dev** [comment]
And teach us how? We will have lots of these in the future.

**Comment by dav-m85** [comment]
backporting and teaching done, check https://github.com/jscad/csg.js/pull/8

**Comment by z3dev** [comment]
@dav-m85 Backport is complete.

Can I close this PR?

**Comment by dav-m85** [comment]
Sure !

Le 25 févr. 2017 7:51 AM, "Z3 Development" <notifications@github.com> a
écrit :

**Comment by Przemyslaw-Marchewka** [comment]
@dav-m85 Thank you very much for help with this commit :) !

**Pull request closed without merging**
