### PR TITLE
Trying to merge development history from openjscad.org

### PR DESCRIPTION
**Pull request by apla**
Hi!

I've started to merge development histories to make one very good codebase instead of three just good:
- https://github.com/joostn/OpenJsCad — yours
- https://github.com/Spiritdude/OpenJSCAD.org — openscad.org
- https://github.com/matiasinsaurralde/atom-scad-preview — atom plugin to edit jscad files

This patch set separate viewer from openscad.js and now viewer supports both `three.js` and `lightgl.js` renderers. I'm preparing patch for openjscad.org too.

Another major change is configuration system — now it allows to configure much more, please take a look `defaults` function from `openscad.viewer.js`

Minor features:
- Display configurable grid;
- HiDPI display support;
- Old options format is supported;
- Colors in configuration can be configured using html hex notation #xxyyzz

### CODE REVIEW

**Comment by joostn** [comment]
Hi Apla,

Would you be willing to do the merge yourself? I don't have time, basically nobody is currently maintaining joostn/OpenJsCad.

**Comment by apla** [comment]
Yes, I will. Thank you!

**Comment by dav-m85** [comment]
Hey, any news on this one ?

**Comment by apla** [comment]
I've rewritten my patch for OpenJSCAD.org, but this patch also need to be rewritten slightly. I'll try my best to finish it in coming week or so.

**Comment by z3dev** [comment]
@apla Given that CSG.js is now part of the JSCAD organization, I believe that this PR is no longer necessary here.

@joostn Would like these changes merged? This might help keep your web interface to current.

**Pull request closed without merging**
